# yaml-language-server: $schema=
# version: "3.7"
# services:
#   sql-server-db:
#     container_name: sql-server-db
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     ports:
#       - "1500:1500"
#     environment:
#       sa_password: "admin"
#       accept_eula: "y"
# docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=12345ABc" -p 1433:1433 --name sqlserver_container -d mcr.microsoft.com/mssql/server:latest
